/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Agenda;

import exceptii.CnpInvalidException;
import exceptii.NrTelefonInvalidException;
import exceptii.NumeInvalidException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutput;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Arrays;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author lili
 */
public class InterfataGrafica extends javax.swing.JFrame implements Serializable {

    private AppConfig appConfig;
    private static InterfataGrafica s_instance;
    private String previousCautareText = "";

    private static int s_randModificareAbonat;

    // reclame
    private List<File> pozeReclame;

    //  date inregistrare user
    String codDeInregistrare = "123";

    // status autoSave
    boolean aFostSalvat = false;

    private CarteDeTelefon modelTabelCarteDeTelefon = new CarteDeTelefon();

    /**
     * Creates new form CarteDeTelefon
     */
    public InterfataGrafica() {
        s_instance = this;
        initComponents();

        appConfig = AppConfig.LoadFromFile();

        populareInformatiiSalvate();

        File dir = new File("src\\reclame");
        pozeReclame = Arrays.asList(dir.listFiles());

        // timer reclame
        javax.swing.Timer timerReclame = new javax.swing.Timer(5000, taskReclame);
        timerReclame.start();

        boolean isRegistered = appConfig.getIsRegistered();
        miInregistrare.setEnabled(!isRegistered);
        miOpen.setEnabled(isRegistered);
        miSave.setEnabled(isRegistered);
        miLogOut.setEnabled(isRegistered);
        jlReclame.setVisible(!isRegistered);
        if (!isRegistered) {
            afisareReclama();
        }

        // timer AutoSave
        javax.swing.Timer timerAutoSave = new javax.swing.Timer(60000 * 5, taskAutoSave);
        timerAutoSave.start();

        tabel.setAutoCreateRowSorter(true);
    }

    ActionListener taskReclame = new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            if (!appConfig.getIsRegistered()) {
                afisareReclama();
            }
        }
    };

    ActionListener taskAutoSave = new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            if (aFostSalvat) {
                salvareDateAbonati(appConfig.getLastSavedFilePath());
            }
        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fc = new javax.swing.JFileChooser();
        jfAdauga = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        tfNume = new javax.swing.JTextField();
        tfPrenume = new javax.swing.JTextField();
        tfTelefon = new javax.swing.JTextField();
        tfCNP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jAdauga = new javax.swing.JButton();
        jAbout = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jfModifica = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        tfNume1 = new javax.swing.JTextField();
        tfPrenume1 = new javax.swing.JTextField();
        tfTelefon1 = new javax.swing.JTextField();
        tfCNP1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        bModifica = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        tfCauta = new javax.swing.JTextField();
        jReclame = new javax.swing.JPanel();
        jlReclame = new javax.swing.JLabel();
        bIesire = new javax.swing.JButton();
        bStergereAbonat = new javax.swing.JButton();
        bAdaugaAbonat = new javax.swing.JButton();
        bModificaAbonat = new javax.swing.JButton();
        jlLastSave = new javax.swing.JLabel();
        jlTimpSalvare = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miOpen = new javax.swing.JMenuItem();
        miSave = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miIesire = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miAdauga = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        miSterge = new javax.swing.JMenuItem();
        miModifica = new javax.swing.JMenuItem();
        miHelp = new javax.swing.JMenu();
        miInregistrare = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        miAbout = new javax.swing.JMenuItem();
        miLogOut = new javax.swing.JMenuItem();

        fc.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        jfAdauga.setLocation(new java.awt.Point(300, 300));
        jfAdauga.setMinimumSize(new java.awt.Dimension(400, 300));

        jPanel1.setMinimumSize(new java.awt.Dimension(300, 200));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 200));

        jLabel1.setText("Nume");

        jLabel2.setText("Prenume");

        jLabel3.setText("CNP");

        jLabel4.setText("nr. telefon");

        jAdauga.setText("Adauga");
        jAdauga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAdaugaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jAdauga, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(tfTelefon)
                    .addComponent(tfCNP)
                    .addComponent(tfPrenume)
                    .addComponent(tfNume))
                .addGap(131, 131, 131))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPrenume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCNP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAdauga)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jfAdaugaLayout = new javax.swing.GroupLayout(jfAdauga.getContentPane());
        jfAdauga.getContentPane().setLayout(jfAdaugaLayout);
        jfAdaugaLayout.setHorizontalGroup(
            jfAdaugaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jfAdaugaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jfAdaugaLayout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)))
        );
        jfAdaugaLayout.setVerticalGroup(
            jfAdaugaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
            .addGroup(jfAdaugaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
        );

        jAbout.setMinimumSize(new java.awt.Dimension(280, 360));
        jAbout.setResizable(false);

        jLabel7.setText("Informatii despre aplicatie:");

        jLabel8.setText("Autor:");

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("Liliana Stan,\nclasa Java 4 nov");
        jTextArea3.setFocusable(false);
        jScrollPane4.setViewportView(jTextArea3);

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jTextArea4.setText("Agenda de telefon permite adaugarea, \nmodificarea si stergerea abonatilor si \nsalvarea locala.\nVersiunea 1.0 - 2018\n");
        jTextArea4.setFocusable(false);
        jScrollPane5.setViewportView(jTextArea4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jAboutLayout = new javax.swing.GroupLayout(jAbout.getContentPane());
        jAbout.getContentPane().setLayout(jAboutLayout);
        jAboutLayout.setHorizontalGroup(
            jAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );
        jAboutLayout.setVerticalGroup(
            jAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jfModifica.setLocation(new java.awt.Point(300, 300));
        jfModifica.setMinimumSize(new java.awt.Dimension(400, 300));

        jPanel3.setMinimumSize(new java.awt.Dimension(300, 200));

        jLabel9.setText("Nume");

        jLabel10.setText("Prenume");

        jLabel11.setText("CNP");

        jLabel12.setText("nr. telefon");

        bModifica.setText("Modifica");
        bModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bModifica, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(tfTelefon1)
                    .addComponent(tfCNP1)
                    .addComponent(tfPrenume1)
                    .addComponent(tfNume1))
                .addGap(131, 131, 131))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNume1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPrenume1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCNP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTelefon1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bModifica)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jfModificaLayout = new javax.swing.GroupLayout(jfModifica.getContentPane());
        jfModifica.getContentPane().setLayout(jfModificaLayout);
        jfModificaLayout.setHorizontalGroup(
            jfModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jfModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jfModificaLayout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jfModificaLayout.setVerticalGroup(
            jfModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jfModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 460));
        setMinimumSize(new java.awt.Dimension(705, 460));
        setName("InterfataPrincipala"); // NOI18N
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jScrollPane1.setMinimumSize(new java.awt.Dimension(645, 25));
        jScrollPane1.setName(""); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(645, 400));

        tabel.setModel(modelTabelCarteDeTelefon);
        tabel.setColumnSelectionAllowed(true);
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        tabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tabelKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);
        tabel.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (tabel.getColumnModel().getColumnCount() > 0) {
            tabel.getColumnModel().getColumn(0).setMinWidth(30);
            tabel.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        tfCauta.setPreferredSize(new java.awt.Dimension(100, 28));
        tfCauta.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfCautaCaretUpdate(evt);
            }
        });

        jReclame.setPreferredSize(new java.awt.Dimension(650, 100));

        jlReclame.setToolTipText("");

        javax.swing.GroupLayout jReclameLayout = new javax.swing.GroupLayout(jReclame);
        jReclame.setLayout(jReclameLayout);
        jReclameLayout.setHorizontalGroup(
            jReclameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlReclame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jReclameLayout.setVerticalGroup(
            jReclameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlReclame, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        bIesire.setText("Iesire");
        bIesire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIesireActionPerformed(evt);
            }
        });

        bStergereAbonat.setText("Stergere Abonat");
        bStergereAbonat.setEnabled(false);
        bStergereAbonat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStergereAbonatActionPerformed(evt);
            }
        });

        bAdaugaAbonat.setText("Adauga Abonat");
        bAdaugaAbonat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdaugaAbonatActionPerformed(evt);
            }
        });

        bModificaAbonat.setText("Modifica Abonat");
        bModificaAbonat.setEnabled(false);
        bModificaAbonat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificaAbonatActionPerformed(evt);
            }
        });

        jlLastSave.setText("Last save:");
        jlLastSave.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel5.setText("Cautare:");

        jMenu1.setMnemonic('f');
        jMenu1.setText("File");

        miOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        miOpen.setMnemonic('o');
        miOpen.setText("Open");
        miOpen.setEnabled(false);
        miOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miOpenActionPerformed(evt);
            }
        });
        jMenu1.add(miOpen);

        miSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        miSave.setMnemonic('s');
        miSave.setText("Save");
        miSave.setEnabled(false);
        miSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSaveActionPerformed(evt);
            }
        });
        jMenu1.add(miSave);
        jMenu1.add(jSeparator1);

        miIesire.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        miIesire.setMnemonic('e');
        miIesire.setText("Iesire");
        miIesire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miIesireActionPerformed(evt);
            }
        });
        jMenu1.add(miIesire);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('a');
        jMenu2.setText("Abonati");

        miAdauga.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        miAdauga.setMnemonic('a');
        miAdauga.setText("Adauga");
        miAdauga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAdaugaActionPerformed(evt);
            }
        });
        jMenu2.add(miAdauga);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setMnemonic('C');
        jMenuItem5.setText("Cauta");
        jMenu2.add(jMenuItem5);

        miSterge.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        miSterge.setMnemonic('S');
        miSterge.setText("Sterge");
        miSterge.setEnabled(false);
        miSterge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miStergeActionPerformed(evt);
            }
        });
        jMenu2.add(miSterge);

        miModifica.setMnemonic('M');
        miModifica.setText("Modifica");
        miModifica.setEnabled(false);
        miModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miModificaActionPerformed(evt);
            }
        });
        jMenu2.add(miModifica);

        jMenuBar1.add(jMenu2);

        miHelp.setMnemonic('h');
        miHelp.setText("Help");

        miInregistrare.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.CTRL_MASK));
        miInregistrare.setMnemonic('i');
        miInregistrare.setText("Inregistrare");
        miInregistrare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miInregistrareActionPerformed(evt);
            }
        });
        miHelp.add(miInregistrare);
        miHelp.add(jSeparator2);

        miAbout.setMnemonic('a');
        miAbout.setText("About");
        miAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAboutActionPerformed(evt);
            }
        });
        miHelp.add(miAbout);

        miLogOut.setMnemonic('l');
        miLogOut.setText("Log Out");
        miLogOut.setEnabled(false);
        miLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogOutActionPerformed(evt);
            }
        });
        miHelp.add(miLogOut);

        jMenuBar1.add(miHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlLastSave, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlTimpSalvare, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jReclame, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfCauta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bAdaugaAbonat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bStergereAbonat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bModificaAbonat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bIesire))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCauta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bIesire)
                    .addComponent(bStergereAbonat)
                    .addComponent(bAdaugaAbonat)
                    .addComponent(bModificaAbonat)
                    .addComponent(jLabel5))
                .addGap(30, 30, 30)
                .addComponent(jReclame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlLastSave)
                    .addComponent(jlTimpSalvare)))
        );

        tfCauta.getAccessibleContext().setAccessibleName("");
        tfCauta.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSaveActionPerformed
        // TODO add your handling code here:
        String folder = "date";
        File fileDefault = new File(folder);
        fc.setCurrentDirectory(fileDefault);
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        fc.addChoosableFileFilter(new FileNameExtensionFilter("*.txt", "txt"));
        if (fc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            //  File dir = fc.getSelectedFile();
            File file = fc.getSelectedFile();
            String caleFisier = file.toString();
            appConfig.setLastSavedFilePath(caleFisier);
            salvareDateAbonati(caleFisier);
            aFostSalvat = true;
        }
    }//GEN-LAST:event_miSaveActionPerformed

    private void bAdaugaAbonatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdaugaAbonatActionPerformed
        jfAdauga.setVisible(true);
    }//GEN-LAST:event_bAdaugaAbonatActionPerformed

    private void miOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miOpenActionPerformed
        String folder = "date";
        File fileDefault = new File(folder);
        fc.setCurrentDirectory(fileDefault);

        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        fc.addChoosableFileFilter(new FileNameExtensionFilter("*.txt", "txt"));
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File fisier = fc.getSelectedFile();
            if (fisier != null && fisier.isFile()) {
                incarcaDateCarteTelefon(fisier.getAbsolutePath());
            }
        }
    }//GEN-LAST:event_miOpenActionPerformed

    private void bStergereAbonatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStergereAbonatActionPerformed
        stergeRandulSelectat();
    }//GEN-LAST:event_bStergereAbonatActionPerformed

    private void miIesireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miIesireActionPerformed
        bIesireActionPerformed(evt);
    }//GEN-LAST:event_miIesireActionPerformed

    private void bIesireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIesireActionPerformed
        // TODO add your handling code here:
        int optiune = JOptionPane.showConfirmDialog(null,
                "Doriti sa parasiti aplicatia?",
                "Iesire",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.INFORMATION_MESSAGE);
        if (optiune == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_bIesireActionPerformed

    private void miInregistrareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miInregistrareActionPerformed
        // TODO add your handling code here:
        String parola = JOptionPane.showInputDialog("Care este parola? Parola este: 123");
        if (codDeInregistrare.compareTo(parola) == 0) {
            System.out.println("Parola este corecta.");
            miInregistrare.setEnabled(false);
            miOpen.setEnabled(true);
            miSave.setEnabled(true);
            appConfig.setIsRegistered(true);
            jlReclame.setVisible(false);
        } else {
            popupMessage("Parola nu este buna", "Eroare", JOptionPane.ERROR_MESSAGE);
        }
        miLogOut.setEnabled(true);
    }//GEN-LAST:event_miInregistrareActionPerformed

    private void jAdaugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdaugaActionPerformed
        try {
            String nume = tfNume.getText();
            String prenume = tfPrenume.getText();
            String cnp = tfCNP.getText();
            String telefon = tfTelefon.getText();
            Abonat a = Abonat.getInstance(nume, prenume, cnp, telefon);

            modelTabelCarteDeTelefon.adaugaAbonat(a);

            tfNume.setText("");
            tfPrenume.setText("");
            tfCNP.setText("");
            tfTelefon.setText("");
            jfAdauga.setVisible(false);
            popupMessage("Abonatul a fost adaugat", "Succes", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            ShowAbonatEditErrorMessage(e);
        }
    }//GEN-LAST:event_jAdaugaActionPerformed

    private void miAdaugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAdaugaActionPerformed
        jfAdauga.setVisible(true);
    }//GEN-LAST:event_miAdaugaActionPerformed

    private void miStergeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miStergeActionPerformed
        bStergereAbonatActionPerformed(evt);
    }//GEN-LAST:event_miStergeActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        stergeRandulSelectat();
    }//GEN-LAST:event_formKeyPressed

    private void miModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miModificaActionPerformed
        modificaAbonatulSelectat(s_randModificareAbonat);
    }//GEN-LAST:event_miModificaActionPerformed

    private void miAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAboutActionPerformed
        jAbout.setVisible(true);
    }//GEN-LAST:event_miAboutActionPerformed

    private void bModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificaActionPerformed
        modificaAbonatulSelectat(s_randModificareAbonat);
    }//GEN-LAST:event_bModificaActionPerformed

    private void bModificaAbonatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificaAbonatActionPerformed
        jfModifica.setVisible(true);

        tfNume1.setText(modelTabelCarteDeTelefon.getValueAt(s_randModificareAbonat, 1).toString());
        tfPrenume1.setText(modelTabelCarteDeTelefon.getValueAt(s_randModificareAbonat, 2).toString());
        tfCNP1.setText(modelTabelCarteDeTelefon.getValueAt(s_randModificareAbonat, 3).toString());
        tfTelefon1.setText(modelTabelCarteDeTelefon.getValueAt(s_randModificareAbonat, 4).toString());

    }//GEN-LAST:event_bModificaAbonatActionPerformed

    private void tfCautaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfCautaCaretUpdate
        String text = tfCauta.getText();
        TableRowSorter<CarteDeTelefon> rowSorter = (TableRowSorter<CarteDeTelefon>) tabel.getRowSorter();
        if (!previousCautareText.equals(text)) {
            rowSorter.setRowFilter(RowFilter.regexFilter(text));
            previousCautareText = text;
        }
    }//GEN-LAST:event_tfCautaCaretUpdate

    private void miLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogOutActionPerformed
        int optiune = JOptionPane.showConfirmDialog(null,
                "Doriti sa va delogati?",
                "Iesire",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.INFORMATION_MESSAGE);
        if (optiune == JOptionPane.YES_OPTION) {
            miInregistrare.setEnabled(true);
            miOpen.setEnabled(false);
            miSave.setEnabled(false);
            appConfig.setIsRegistered(false);
            jlReclame.setVisible(true);
            miLogOut.setEnabled(false);
        }
    }//GEN-LAST:event_miLogOutActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        int rand = tabel.getSelectedRow();
        s_randModificareAbonat = rand;
        bModificaAbonat.setEnabled(true);
        bStergereAbonat.setEnabled(true);
        miModifica.setEnabled(true);
        miSterge.setEnabled(true);
    }//GEN-LAST:event_tabelMouseClicked

    private void tabelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelKeyTyped
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_DELETE:
                stergeRandulSelectat();
            default:
                break;
        }
    }//GEN-LAST:event_tabelKeyTyped

    private void stergeRandulSelectat() {
        int selectedIndex = tabel.getSelectedRow();
        if (tabel.isRowSelected(selectedIndex)) {
            int optiune = JOptionPane.showConfirmDialog(null,
                    "Doriti sa stergeti abonatul?",
                    "Stergere Abonat",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.INFORMATION_MESSAGE);
            if (optiune == JOptionPane.YES_OPTION) {
                modelTabelCarteDeTelefon.removeAbonat(selectedIndex);
            }
        }
    }

    private void modificaAbonatulSelectat(int rand) {
        try {
            String nume = tfNume1.getText();
            String prenume = tfPrenume1.getText();
            String cnp = tfCNP1.getText();
            String telefon = tfTelefon1.getText();

            Abonat a = Abonat.getInstance(nume, prenume, cnp, telefon);
            modelTabelCarteDeTelefon.modificaAbonat(rand, a);

            jfModifica.setVisible(false);

            popupMessage("Abonatul a fost modificat", "Succes", JOptionPane.INFORMATION_MESSAGE);
        } catch (NumeInvalidException e) {
            popupMessage("Nume invalid", "Eroare", JOptionPane.ERROR_MESSAGE);
        } catch (CnpInvalidException e) {
            popupMessage("CNP invalid", "Eroare", JOptionPane.ERROR_MESSAGE);
        } catch (NrTelefonInvalidException e) {
            popupMessage("Nr de telefon invalid", "Eroare", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException e) {
            popupMessage(e.getMessage(), "Eroare", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfataGrafica.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfataGrafica.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfataGrafica.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfataGrafica.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfataGrafica().setVisible(true);
            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdaugaAbonat;
    private javax.swing.JButton bIesire;
    private javax.swing.JButton bModifica;
    private javax.swing.JButton bModificaAbonat;
    private javax.swing.JButton bStergereAbonat;
    private javax.swing.JFileChooser fc;
    private javax.swing.JFrame jAbout;
    private javax.swing.JButton jAdauga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jReclame;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JFrame jfAdauga;
    private javax.swing.JFrame jfModifica;
    private javax.swing.JLabel jlLastSave;
    private javax.swing.JLabel jlReclame;
    private javax.swing.JLabel jlTimpSalvare;
    private javax.swing.JMenuItem miAbout;
    private javax.swing.JMenuItem miAdauga;
    private javax.swing.JMenu miHelp;
    private javax.swing.JMenuItem miIesire;
    private javax.swing.JMenuItem miInregistrare;
    private javax.swing.JMenuItem miLogOut;
    private javax.swing.JMenuItem miModifica;
    private javax.swing.JMenuItem miOpen;
    private javax.swing.JMenuItem miSave;
    private javax.swing.JMenuItem miSterge;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField tfCNP;
    private javax.swing.JTextField tfCNP1;
    private javax.swing.JTextField tfCauta;
    private javax.swing.JTextField tfNume;
    private javax.swing.JTextField tfNume1;
    private javax.swing.JTextField tfPrenume;
    private javax.swing.JTextField tfPrenume1;
    private javax.swing.JTextField tfTelefon;
    private javax.swing.JTextField tfTelefon1;
    // End of variables declaration//GEN-END:variables

    private void popupMessage(String message, String eroare, int tip) {
        JOptionPane.showMessageDialog(this, message, eroare, tip);
    }

    private void populareInformatiiSalvate() {
        incarcaDateCarteTelefon(appConfig.getLastSavedFilePath());
    }

    private void incarcaDateCarteTelefon(String caleFisier) {
        try {
            // TODO add checks
            // - verify that file exists
            // - verify that isn't corrupted
            // and show error messages

            File file = new File(caleFisier);
            FileInputStream fr = new FileInputStream(file.getAbsoluteFile());
            BufferedInputStream br = new BufferedInputStream(fr);
            ObjectInputStream or = new ObjectInputStream(br);

            List<Abonat> abonati = (List<Abonat>) or.readObject();
            if (abonati != null) {
                modelTabelCarteDeTelefon.seteazaAbonati(abonati);
            }

            or.close();
            br.close();
            fr.close();
        } catch (Exception e) {
            e.printStackTrace();
            Logger
                    .getLogger(InterfataGrafica.class
                            .getName()).log(Level.SEVERE, null, e);
        }
    }

    private void afisareReclama() {
        //File calePozaCurenta = pozeReclame.get(reclamaCurenta);
        if (pozeReclame.isEmpty()) {
            return;
        }

        int nrPoza = (int) (Math.random() * pozeReclame.size());
        File calePozaCurenta = pozeReclame.get(nrPoza);
        ImageIcon poza = new ImageIcon(calePozaCurenta.getAbsolutePath());
        jlReclame.setIcon(poza);
    }

    private void salvareDateAbonati(String caleFisier) {
        File file = new File(caleFisier);
        try {
            if (!file.exists()) {
                file.createNewFile();
            }
            FileOutputStream fw = new FileOutputStream(file.getAbsoluteFile());
            BufferedOutputStream bw = new BufferedOutputStream(fw);
            ObjectOutput ow = new ObjectOutputStream(bw);

            ow.writeObject(modelTabelCarteDeTelefon.getAbonati());

            ow.close();
            bw.close();
            fw.close();
        } catch (Exception e) {
            e.printStackTrace();
            Logger
                    .getLogger(InterfataGrafica.class
                            .getName()).log(Level.SEVERE, null, e);
        }

        // afisarea timpului in jlabel
        String textOra = formatareTimp(LocalDateTime.now());
        jlTimpSalvare.setText(textOra);
        jlLastSave.setEnabled(true);
    }

    private String formatareTimp(LocalDateTime ldt) {
        Locale RO = new Locale("ro", "RO");
        return ldt.format(DateTimeFormatter.ofPattern(" 'ora' HH:mm", RO)).toString();
    }

    public static void ShowAbonatEditErrorMessage(Exception e) {
        if (e instanceof NumeInvalidException) {
            s_instance.popupMessage("Nume invalid", "Eroare", JOptionPane.ERROR_MESSAGE);
        } else if (e instanceof CnpInvalidException) {
            s_instance.popupMessage("CNP invalid", "Eroare", JOptionPane.ERROR_MESSAGE);
        } else if (e instanceof NrTelefonInvalidException) {
            s_instance.popupMessage("Nr de telefon invalid", "Eroare", JOptionPane.ERROR_MESSAGE);
        } else if (e instanceof IllegalArgumentException) {
            s_instance.popupMessage(e.getMessage(), "Eroare", JOptionPane.ERROR_MESSAGE);
        } else {
            s_instance.popupMessage(e.getMessage(), "Eroare", JOptionPane.ERROR_MESSAGE);
        }
    }
}
